### ISSUE TITLE
Write tests for php server

### ISSUE THREAD

**Issue by Liima** [MCLACS/CSCI452-FA17-Public#1]
__To complete this issue, we need two python files containing our tests for #3 and #2 respectively.__

#### Root path
When a user goes to the root url:
* server should send 200 response message
* server should send a HTML document

#### Snippets index path
When a user goes to the snippets index path:
* server should send 200 response message
* server should send a JSON response
  * JSON should contain a key snippets with an array type
  * each element in snippets array should be an object
  * each object in snippets array should contain properties ID (int), creator (string), description (string), language (string)

**Comment by JPhilibert** [comment]
description: create python script to automatically test the functionality of the root and list snippets

**Comment by MCLACS** [comment]
This looks great!  One comment -- I don't think you need to test the root URL yet.  A root URL is not required for the user story (VS1) and does not belong in this spring.
