### ISSUE TITLE
Design and Create a Skeleton Sketch for the Desktop View of the SPA

### ISSUE THREAD

**Issue by Pappyhands** [MCLACS/CSCI452-FA17-Public#10]
**To complete this task, we need to create tangible representations of how the Single-Page Application basic structure would appear on the Desktop platform and have it display a list of snippets, once created we would then document these sketches within this issue and in #general within the Slack.**

These sketches will most likely be done using InVision or Photoshop. If we decide to use Photoshop I feel it would also be a good idea to attach the original PSD files here as well.

**Comment by MCLACS** [comment]
OK, so this is a great start.  But I think you are getting ahead of yourselves here.  The first user story says nothing about mobile views.  All you have to do for this sprint is implement VS1 and VS1 just says you have to show a list of snippets.  Rewrite this task to be more specific to the sprint you are working on.  Your UI will evolve over time as you implement more sprints and user stories.

**Comment by Pappyhands** [comment]
@MCLACS ok mark I am rewriting the task right now
