### ISSUE TITLE
Discuss game plan and being to implement HTML and CSS in a way that replicates previously drawn sketches

### ISSUE THREAD

**Issue by Pappyhands** [MCLACS/CSCI452-FA17-Public#11]
**To complete this task, we need to properly configure out Cloud9 account with Bootstrap and the proper filing scheme than begin to implement HTML and CSS that can be used to display a list of snippets. For each snippet the author, language, and description should be shown.**

This step is dependent on the completion of the sketches for the __Desktop Platform__. The overall goal is to create a dynamically changing UI that scales with the User's screen resolution, regardless of the device they choose to view it on. This UI would display a list of snippets via JS.

**Comment by nsteward96** [comment]
Isn't Bootstrap simply implemented with a script tag? You should then be able to use it within the HTML. Unless this issue is implementing the bootstrap styling itself into the HTML.

**Comment by Pappyhands** [comment]
@nsteward96 we planned on simply using the Bootstrap CDN via a script tag like you said. More or less I was just trying to write a detailed task. The actual implementation of Bootstrap is very easy as I'm sure you know.

**Comment by MCLACS** [comment]
This task needs to be more specific.  For example, implement HTML and CSS that can be used to display a list of snippets. For each snippet the author, language, and description should be shown.

**Comment by Pappyhands** [comment]
editing task w/ Mark's suggestions.
