### ISSUE TITLE
VS1: php-team: Retrieve DB schema from sql-team

### ISSUE THREAD

**Issue by Liima** [MCLACS/CSCI452-FA17-Public#4]
__To complete this issue, we need to speak to the sql-team and get a schema or ERD from them, and post it to this issue.__

**Comment by Liima** [comment]
#### VS1 ERD
Thanks to sql-team for their fast response and to @JPhilibert for retrieving it from them.
![pasted image at 2017_09_08 07_10 pm](https://user-images.githubusercontent.com/4086844/30245305-bba4e1f6-95a2-11e7-9ebb-67fdcfadb95e.png)

**Comment by Liima** [comment]
https://files.slack.com/files-pri/T6Z3TM588-F71DQ076D/pasted_image_at_2017_09_12_01_35_pm.png

**Comment by MarioChase** [comment]
This should be the final ERD I was hoping for a bit more feedback before handing it off but you guys seem to be ok with it. This is the bare bones ERD still have a little more to go before the database is set up but it shouldn't take long. Keep in touch if something doesn't seem right.
