### ISSUE TITLE
Write and deliver API documentation to javascript team

### ISSUE THREAD

**Issue by Liima** [MCLACS/CSCI452-FA17-Public#5]
__To complete this task, we need to write API documentation for the addition of the snippets list path we are implementing in VS1, post it in this issue, and on the javascript-team slack channel__

Additionally, I think we should want to start an API documentation page on the project wiki so future updates to the API can be followed by the team.

**Comment by MCLACS** [comment]
This task is too general.  This implies that the API documentation is going to be complete.  You need to be more specific.  For the first user story you really just need to provide **one** API call: the call to get a list of snippets.  So this task should be something like _**"write API documentation for getting a list of snippets and communicate it with the JS team"**_.

**Comment by Liima** [comment]
Draft for API:


'/CSCI452-FA17-Public/Server/php/crud.php?cmd=list'
``` json
{
  "snippets": [
    {
       id: (int),
       creator: (string),
       description: (string),
       language: (string),
     },... 
  ]
}
```

**Comment by Liima** [comment]
@MCLACS I updated the task to concern only the changes to the API made in VS1.
