### ISSUE TITLE
Write and deliver Schema to php team

### ISSUE THREAD

**Issue by MarioChase** [MCLACS/CSCI452-FA17-Public#6]
**To complete this task, a Schema will be developed with the standardization of table and variable names. It will then be posted here and in the php-team slack channel.**

This needs the ERD to be completed.

**Comment by MCLACS** [comment]
IS this going to be a sql file that contains the SQL comments that creates the schema?  Or is this an ERD?  I think you need both.  Perhaps you can break this into two tasks?
